[project]
name = "rh-pulze-azure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.129.0",
    "joblib>=1.5.3",
    "pytest>=9.0.2",
    "seaborn>=0.13.2",
    "uvicorn>=0.41.0",
]
